DROP DATABASE IF EXISTS `OHJ_EXAM`;
CREATE DATABASE `OHJ_EXAM`;
USE `OHJ_EXAM`;

# spot 테이블 생성
CREATE TABLE spot(
    id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    city CHAR(100) NOT NULL,
    spot_name CHAR(100) NOT NULL,
    location CHAR(100) NOT NULL,
    initialDate DATE NOT NULL,
    updateDate DATE NOT NULL,
    `area` INT(255) NOT NULL,
    etc CHAR(255) NOT NULL
);
		
SELECT *
FROM spot

# answer 테이블 생성
CREATE TABLE answer(
    id INT(10) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    answer CHAR(255) NOT NULL;
);
	
